### PR TITLE
Add link for summernote-video-attributes

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by lqez** [comment]
@StudioJunkyard, really appreciate for gardening Summernote. Thanks.

**Comment by ghost** [comment]
lol Gardening, never thought of that one before.

**Comment by lqez** [comment]
I'd alway thought that 'gardening' is the most important part of OSS eco system. 🏡

**Comment by ghost** [comment]
I'd just not heard it like that before, I like it.

**Pull request merged**
