### PR TITLE
Add summernote-audio into Insert section

### PR DESCRIPTION
**Pull request by lqez**
https://github.com/taalendigitaal/summernote-audio
/cc @hendrismit

### CODE REVIEW

**Comment by hendrismit** [comment]
Awesome! ;)

**Comment by DennisSuitters** [comment]
Looks like a great addition @lqez was there something specifically want me to do?

**Comment by lqez** [comment]
@DiemenDesign Just double check, nothing special. Please merge it if there is no problem.

**Comment by DennisSuitters** [comment]
Some of the options are missing in the options area, when I tried to upload a 1.9MB mp3 to test on my local machine it won't do it, because there are no vars available for the script to set the maximum file size.
Also, in the icon, if you use just "note-icon", you can remove the extra css file, as I found the vertical align unnecessary.
@hendrismit if you could fix those that would be great, you've done some good work on this.

**Comment by DennisSuitters** [comment]
@hendrismit I've merged this PR in the hopes to spur you to fix the issues in your Plugin. Audio doesn't seem to be something a lot of other people have thought about including, but I feel it is something worth adding for those people that have things like podcasts in their websites.

**Pull request merged**
