### PR TITLE
Add Link for summernote-templates

### PR DESCRIPTION
**Pull request by DennisSuitters**
This is more interactive with pick and insert point and click template selection.

### CODE REVIEW

**Comment by lqez** [comment]
This PR has two problems:

1. Typo in the name
2. Please order it in alphabetical order, by ascending. (please refer [Travis's build log](https://travis-ci.org/summernote/awesome-summernote/builds/303034294?utm_source=github_status&utm_medium=notification))

**Comment by DennisSuitters** [comment]
Ooops, my bad. I thought I had placed it alphabetically, I'll get onto that.

**Comment by DennisSuitters** [comment]
oh ok, the typo made travis reorder the change in the list, that must be why it appeared to be out of order.

**Comment by lqez** [comment]
Cool!

**Pull request merged**
