### PR TITLE
Add summernote-image-title plugin

### PR DESCRIPTION
**Pull request by asiffermann**
I saw several issues and pull requests ([#754](https://github.com/summernote/summernote/pull/754) and [#472](https://github.com/summernote/summernote/issues/472)) on Summernote repository, but as I needed this feature on my project, I created an independant plugin to edit alt and title attributes on an image.

Maybe it could help someone for now!

Thanks :)

### CODE REVIEW

**Comment by ghost** [comment]
Just been playing with your plugin, nice work. I have a couple of suggestions for improvements, well additions more so. The alt and title attributes may not always contain the same content, having those editable separately would be good. Also, being able to add a class to images would be cool, either by a text input, or selectable drop down to restrict choices, maybe if there was an option to add class names that would make the dialog display a drop down, or if the options aren't set or empty it could display an input field.

**Comment by ghost** [comment]
Just had another thought, it would be cool if we could add these options to the image popover when selecting images.

**Comment by asiffermann** [comment]
Hi @StudioJunkyard and thanks for trying out my little plugin ! :)

I agree with you, I should define an option on my plugin to let people decide if they want to set the title and alt attributes together or not.
Could you please open an issue on my repository, and I will do this as soon as possible?

Concerning the class feature, maybe you could use [this other plugin](https://github.com/creativeprogramming/summernote-addclass). I just tried to add his button on an image popover and it works well : [working example](https://jsfiddle.net/dtgr5q29/55/).

**Comment by ghost** [comment]
Oh, yeah, I've seen the Class add on before. I've been playing with your code, and already added the alt, and class options via input fields. I've also taken the liberty of tidying up the dialog markup. I'll paste this as an issue like you asked, so you can pick and choose what to keep.

**Comment by ghost** [comment]
I've opened the issue, and just updated it again. I've added a Style option input, and tidied up the dialog a bit more.

Now I need to learn how to add a pull request so I can add the save button plugin I made.

**Comment by lqez** [comment]
:beers: Cheers!

**Pull request merged**
