### PR TITLE
Plugin to get SEO type Data from Editor Text

### PR DESCRIPTION
**Pull request by ghost**
This Plugin adds a Dropdown menu with selections to get data from the the editors text, for Keywords, Caption, and Description, and placing that selection into a designated element, either an Input or HTML type Element, which can also be auto submitted to save using jQuery's `.trigger("change")`

### CODE REVIEW

**Comment by lqez** [comment]
@StudioJunkyard Thanks!. Could you make a demo page of it (maybe via github pages) ?

**Comment by ghost** [comment]
Yeah, I should do something, just been so busy. I've been creating these plugins with the evolution of LibreCMS, which has Summernote as it's WYSIWYG Editor, the plugins are a progression of features needed for my web client's. I was thinking of eventually doing a gh-page for LibreCMS, with a section with addons, and the examples of the plugins I've created, which can be linked to from the repo page.

**Comment by ghost** [comment]
Took your advice, and created a quick demo page. I should do this for the other plugins as well.

http://studiojunkyard.github.io/summernote-seo/

**Comment by lqez** [comment]
@StudioJunkyard Awesome. Did you have a problem with its svg icon?

**Comment by ghost** [comment]
Oh, I think that's due to not including the class I edited to use SVG Icons with the SVG Theme I made.

**Pull request merged**
